### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 1198287349** [maoabc/nmmp#1]
Exception in thread "main" java.rmi.RemoteException: Can't handle main dex
        at com.nmmedit.apkprotect.ApkProtect.handleApplicationClass(ApkProtect.java:516)
        at com.nmmedit.apkprotect.ApkProtect.run(ApkProtect.java:119)
        at com.nmmedit.protect.Main.main(Main.java:58)

**Comment by maoabc** [comment]
错误应该是删除中间dex时出错了，不知道是不是没生成，还是文件操作时出错

**Comment by 1198287349** [comment]
> 错误应该是删除中间dex时出错了，不知道是不是没生成，还是文件操作时出错

没有删除啊  我看到dex生成了 就是没出app

**Comment by 1198287349** [comment]
> 错误应该是删除中间dex时出错了，不知道是不是没生成，还是文件操作时出错

留个联系方式呗

**Comment by 1198287349** [comment]
> 错误应该是删除中间dex时出错了，不知道是不是没生成，还是文件操作时出错

我是在win10下面编译和使用的

**Comment by 1198287349** [comment]
Exception in thread "main" java.rmi.RemoteException: Can't handle main dex
        at com.nmmedit.apkprotect.ApkProtect.handleApplicationClass(ApkProtect.java:516)
        at com.nmmedit.apkprotect.ApkProtect.run(ApkProtect.java:119)
        at com.nmmedit.protect.Main.main(Main.java:58)

**Comment by 1198287349** [comment]
一直都是这个错误

**Comment by maoabc** [comment]
我改了下，等外提交

**Comment by 1198287349** [comment]
> 我改了下，等外提交

等你修改

**Comment by maoabc** [comment]
win10的话可能有问题，就算这个没问题，后面编译也不行，因为用了shell脚本以及文件路径全按linux下的方式处理

**Comment by 1198287349** [comment]
> win10的话可能有问题，就算这个没问题，后面编译也不行，因为用了shell脚本以及文件路径全按linux下的方式处理

等会装一下乌班图去试试

**Comment by 1198287349** [comment]
> Task :arsc:test FAILED

apk.arsc.ResourceStringTest > decodeUtf8String FAILED
    java.lang.AssertionError at ResourceStringTest.java:85

apk.arsc.ResourceStringTest > encodeUtf8String FAILED
    java.lang.AssertionError at ResourceStringTest.java:97

apk.arsc.ResourceStringTest > decodeUtf16String FAILED
    java.lang.AssertionError at ResourceStringTest.java:91

apk.arsc.ResourceStringTest > encodeUtf16String FAILED
    java.lang.AssertionError at ResourceStringTest.java:103

16 tests completed, 4 failed

**Comment by maoabc** [comment]
这个是arsc测试出错，不知道是不是跟jdk版本有关。用jdk1.8试试呢，高版本jdk我没试过。这些来自arscblamer，用来直接修改二进制AndroidManifest.xml。

**Comment by 1198287349** [comment]
> 这个是arsc测试出错，不知道是不是跟jdk版本有关。用jdk1.8试试呢，高版本jdk我没试过。这些来自arscblamer，用来直接修改二进制AndroidManifest.xml。

也是一样的

**Comment by maoabc** [comment]
找个出错的测试方法调试看看哪步出错的呢，按里这些应该不会有问题。实在不行把测试代码全给注释掉。

**Comment by comeon010** [comment]
不如上传一个样本，给作者用于分析

**Comment by maoabc** [comment]
好的，我晚上弄个例子，我以为这种java项目很好编译，估计有的地方依赖我本地环境，导致有错误

**Comment by TimScriptov** [comment]
> Exception in thread "main" java.rmi.RemoteException: Can't handle main dex
> at com.nmmedit.apkprotect.ApkProtect.handleApplicationClass(ApkProtect.java:516)
> at com.nmmedit.apkprotect.ApkProtect.run(ApkProtect.java:119)
> at com.nmmedit.protect.Main.main(Main.java:58)

I have met this error. I "Rebuild project nmmp" and it worked.
