### ISSUE TITLE
nmm-protect加固时针对新版androidstudio中Composeui框架存在MaterialTheme会抱错并崩溃

### ISSUE THREAD

**Issue by GTZCrow** [maoabc/nmmp#103]
java.lang.IncompatibleClassChangeError：找到界面androidx.compose.ui.graphics.drawscope.DrawScope，但类是预期的（base.apk中出现“androidx.compose.ui.graphics.drawscope.DrawScope”声明）atandroidx.compose.ui.graphics.drawscope.DrawScope.drawRect-n-J9OG0$default（DrawScope.kt:410）at an.compose.foundation.Background.drawRect（Background.kt:111）at andr.compose.foundation.Background.draw（Background.kt:103）at androi.compose.ui.node.BackwardsCompatNode.draw（BackwardsCompatNode.kt:361）at androidx.compose.ui.node.LayoutNodeDrawScope.draw-x_KDEd0$ui_release（LayoutNodeDrawScope.kt:92）at androidx.c.ui.node.NodeCoordinator.drawContainedDrawModifiers（NodeCoordinator.kt:370）at androidx.com.ui.node.NodeCoordinator.draw（NodeCoordinator.kt:359）at androidx.compo.ui.node.LayoutModifierNodeCoordinator.performDraw（LayoutModifierNodeCoordinator.kt:236）at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers（NodeCoordinator.kt:367）at androidx.compose.u.node.NodeCoordinator.access$drawContainedDrawModifiers（NodeCoordinator.kt:58）at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke（NodeCoordinator.kt:396）at androidx.compose.ui.no.NodeCoordinator$invoke$1.invoke（NodeCoordinator.kt:395）at androidx.compose.runtime.snapshots.Snapshot$Companion.observe（Snapshot.kt：2200）at androidx.compose.runtime.s.SnapshotStateObserver$observeReads$1$1.invoke（SnapshotStateObserver.kt:234）at androidx.compose.runtime.sna.SnapshotStateObserver$observeReads$1$1.invoke（SnapshotStateObserver.kt:230）at androidx.compose.runtime.Snaps__DerivedStateKt.observeDerivedStateRecalculations（DerivedState.kt:341）at androidx.compose.runtime.Snapsho.observeDerivedStateRecalculations（未知来源：1）at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads（SnapshotStateObserver.kt:230）at androidx.compose.ui.node.OwnerSnapsh.observeReads$ui_release（OwnerSnapshotObserver.kt:120）at androidx.compose.ui.node.NodeCoordinat.invoke（NodeCoordinator.kt:395）at androidx.compose.ui.node.NodeCoordinator.invoke（NodeCoordinator.kt:58）at androidx.compose.ui.platform.RenderNodeApi29.record（RenderNodeApi29.android.kt:209）at androidx.compose.ui.platform.RenderNodeLayer.updateDisplayList（RenderNodeLayer.android.kt:301）at androidx.compose.ui.platform.RenderNodeLayer.d（RenderNodeLayer.android.kt:242）at androidx.compose.ui.node.NodeCoordinator.draw(No.kt：354）at androidx.compose.ui.node.LayoutNode.draw$ui_releas（LayoutNode.kt:865）at androidx.compose.ui.node.InnerNodeCoordinator.perfor（InnerNodeCoordinator.kt:151）at androidx.compose.ui.node.NodeCoordinator.drawContained（NodeCoordinator.kt:367）at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordi.kt:359）at androidx.compose.ui.node.LayoutNode.draw$ui_release(Layout.kt:865）at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw（AndroidComposeView.android.kt：1041）at android.view.View.draw(View.java:21978)at android.view.View.updateDisplayListIfDirty(View.java:20852)at android.view.View.draw(View.java:21707)at android.view.ViewGroup.drawChild(ViewGroup.java:4432)at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)at android.view.View.updateDisplayListIfDirty(View.java:20843)at android.view.View.draw(View.java:21707)at android.view.ViewGroup.drawChild(ViewGroup.java:4432)at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)at android.view.View.updateDisplayListIfDirty(View.java:20843)at android.view.View.draw(View.java:21707)at android.view.ViewGroup.drawChild(ViewGroup.java:4432)at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)at android.view.View.updateDisplayListIfDirty(View.java:20843)at android.view.View.draw(View.java:21707)at android.view.ViewGroup.drawChild(ViewGroup.java:4432)

**Comment by GTZCrow** [comment]
加固规则不管是什么都会抱错 空和class *都存在这个问题

**Comment by super963883929** [comment]
请问这个问题现在解决了吗

**Comment by wuxiaojun123** [comment]
请问这个问题解决了吗
