### ISSUE TITLE
加固后apk证书似乎损坏了

### ISSUE THREAD

**Issue by crowforkotlin** [maoabc/nmmp#120]
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl347741120.tmp/base.apk: Attempt to get length of null array]

场景复现
java -jar .\vm-protect-2023-07-08-0942.jar apk .\xxx.apk convertRules.txt mapping.txt

convertRules和mapping都是空文件

上述输入后等待打包完成后 通过adb安装出现了问题
尝试不带入convertRules.txt 和 mapping.txt

java -jar .\vm-protect-2023-07-08-0942.jar
也出现了上述报错

**Comment by crowforkotlin** [comment]
签名校验不通过了
app默认开启了v1 + v2 + v3

**Comment by crowforkotlin** [comment]
我发现规则文件都不填写，打包出来后的内容都是没有加固的，apk体积增加了一点，但是却没法安装，原因是签名校验不通过，然后我通过np管理器重新给打出来的apk添加签名却提示
![c3a140bc015f0c4b062ab38c00b81fcf](https://github.com/user-attachments/assets/4407f5f8-1eda-4301-aeeb-596289715884)
![f7e2c0bd3d2e9ac91ff5615643557658_720](https://github.com/user-attachments/assets/d7efb78d-3e03-4382-af79-3680bea447ca)

**Comment by crowforkotlin** [comment]
![1eef2790fdb77955d0b25f91c4b04dd4](https://github.com/user-attachments/assets/993252d6-58ff-40f0-a290-2bbf1cd598a4)
![f7e2c0bd3d2e9ac91ff5615643557658_720](https://github.com/user-attachments/assets/28313f45-174e-44a1-b5aa-f439ee002967)

利用NP管理器对这个加固后的apk重新校验签名也报错了。这个apk里面用了其他so库，采用v1+v2+v3签名，我再换一个干净点的apk试试

**Comment by crowforkotlin** [comment]
改成class androidx.compose.*就好了
但是问题是 直接报错了，和 #103 一样的问题

**Comment by crowforkotlin** [comment]
> 规则不是过滤规则，是转换规则。

好的，谢谢大佬

1. 我目前理解convert.txt是转换规则，用于转换对应的类？

2. README中提到了“无转换规则文件，则会转换dex里所有class里的方法”，但是第一次示例命令中包含了
convert.txt 和 mapping.txt 这个是允许convert.txt支持的内容进行转换？那mapping的作用呢，映射？是指什么，不太理解。

3. 另外我想问一下关于#103的问题有办法解决吗？我在用compose + apk加固的过程中也遇到了这个问题

**Comment by maoabc** [comment]
mapping.txt是proguard混淆生成的文件，用来还原混淆后的类名方法名。
具体不清楚，我没用过那东西，看报错好像是class版本不兼容。还有就是不要去处理开源库，纯粹给逆向者提供指令映射规则

**Comment by super963883929** [comment]
我也遇到这个问题了 
` java.lang.IncompatibleClassChangeError: Found interface androidx.compose.ui.graphics.drawscope.DrawScope, but class was expected (declaration of 'androidx.compose.ui.graphics.drawscope.DrawScope' appears in /data/app/~~BLOGJeg6BX5c5fKzHw3Aww==/com.android.file.ai-38oXE1AQ4BqtXpU9uko2Zw==/base.apk!classes2.dex)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at androidx.compose.ui.graphics.drawscope.DrawScope.drawRect-n-J9OG0$default(DrawScope.kt:490)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at androidx.compose.foundation.BackgroundNode.drawRect(Background.kt:178)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at androidx.compose.foundation.BackgroundNode.draw(Background.kt:159)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at androidx.compose.ui.node.LayoutNodeDrawScope.drawDirect-eZhPAX0$ui_release(LayoutNodeDrawScope.kt:110)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at androidx.compose.ui.node.LayoutNodeDrawScope.draw-eZhPAX0$ui_release(LayoutNodeDrawScope.kt:89)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:450)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at androidx.compose.ui.node.NodeCoordinator.access$drawContainedDrawModifiers(NodeCoordinator.kt:58)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at androidx.compose.ui.node.NodeCoordinator$drawBlock$1$1.invoke(NodeCoordinator.kt:469)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at androidx.compose.ui.node.NodeCoordinator$drawBlock$1$1.invoke(NodeCoordinator.kt:468)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2441)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:502)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:258)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at androidx.compose.ui.node.NodeCoordinator$drawBlock$1.invoke(NodeCoordinator.kt:468)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at androidx.compose.ui.node.NodeCoordinator$drawBlock$1.invoke(NodeCoordinator.kt:466)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at androidx.compose.ui.platform.GraphicsLayerOwnerLayer$recordLambda$1.invoke(GraphicsLayerOwnerLayer.android.kt:291)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at androidx.compose.ui.platform.GraphicsLayerOwnerLayer$recordLambda$1.invoke(GraphicsLayerOwnerLayer.android.kt:289)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at androidx.compose.ui.graphics.layer.GraphicsLayerV29.record(GraphicsLayerV29.android.kt:245)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at androidx.compose.ui.graphics.layer.GraphicsLayer.recordInternal(AndroidGraphicsLayer.android.kt:430)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at androidx.compose.ui.graphics.layer.GraphicsLayer.record-mL-hObY(AndroidGraphicsLayer.android.kt:423)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at androidx.compose.ui.platform.GraphicsLayerOwnerLayer.updateDisplayList(GraphicsLayerOwnerLayer.android.kt:284)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at androidx.compose.ui.platform.GraphicsLayerOwnerLayer.drawLayer(GraphicsLayerOwnerLayer.android.kt:229)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:434)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:1000)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:196)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:447)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:439)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:1000)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:1564)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.view.View.draw(View.java:23331)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.view.View.updateDisplayListIfDirty(View.java:22187)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.view.View.draw(View.java:23053)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.view.ViewGroup.drawChild(ViewGroup.java:4543)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4301)
2025-01-20 16:07:19.798 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.view.View.updateDisplayListIfDirty(View.java:22178)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.view.View.draw(View.java:23053)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.view.ViewGroup.drawChild(ViewGroup.java:4543)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4301)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.view.View.updateDisplayListIfDirty(View.java:22178)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.view.View.draw(View.java:23053)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.view.ViewGroup.drawChild(ViewGroup.java:4543)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4301)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.view.View.updateDisplayListIfDirty(View.java:22178)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.view.View.draw(View.java:23053)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.view.ViewGroup.drawChild(ViewGroup.java:4543)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4301)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.view.View.draw(View.java:23331)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at com.android.internal.policy.DecorView.draw(DecorView.java:892)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.view.View.updateDisplayListIfDirty(View.java:22187)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:690)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:795)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4823)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4524)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3738)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2476)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9331)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1390)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1398)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.view.Choreographer.doCallbacks(Choreographer.java:1040)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.view.Choreographer.doFrame(Choreographer.java:954)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1370)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.os.Handler.handleCallback(Handler.java:942)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.os.Handler.dispatchMessage(Handler.java:99)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.os.Looper.loopOnce(Looper.java:210)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.os.Looper.loop(Looper.java:299)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at android.app.ActivityThread.main(ActivityThread.java:8123)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at java.lang.reflect.Method.invoke(Native Method)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
2025-01-20 16:07:19.799 16570-16570 DEBUG                   com.android.file.ai                  E  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)`

看来对于谷歌的新框架兼容不太行

**Comment by snow548** [comment]
用apktool 对apk 反编译再重新打包

**Comment by fanqieVip** [comment]
> 用apktool 对apk 反编译再重新打包
我用apktool最新版也遇到这个问题，难办，有没有什么办法解决啊？
