### ISSUE TITLE
windows 系统支持编译么？

### ISSUE THREAD

**Issue by JAYAndroid** [maoabc/nmmp#19]
你好，我在windows服务端搭建，按照要求配置好了环境变量，编译报错，请问如何修正呢？
C:\Users\Administrator> java -jar C:\nmm-protect-vm.jar C:\jimian_2.0.10.4.apk

[C:\android-sdk\cmake\3.10.2.4988404\bin\cmake, -HC:\build\dex2c, -DCMAKE_TOOLCHAIN_FILE=C:\android-sdk\ndk\21.1.6352462
\build\cmake\android.toolchain.cmake, -DCMAKE_BUILD_TYPE=Release, -DANDROID_ABI=armeabi-v7a, -DANDROID_NDK=C:\android-sd
k\ndk\21.1.6352462, -DANDROID_PLATFORM=android-21, -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a, -DCMAKE_ANDROID_NDK=C:\android-
sdk\ndk\21.1.6352462, -DCMAKE_EXPORT_COMPILE_COMMANDS=ON, -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\build\obj\armeabi-v7a, -DC
MAKE_MAKE_PROGRAM=C:\android-sdk\cmake\3.10.2.4988404\bin\ninja, -DCMAKE_SYSTEM_NAME=Android, -DCMAKE_SYSTEM_VERSION=21,
 -BC:\build\.cxx\cmake\Release\armeabi-v7a, -GNinja]
-- Check for working C compiler: C:/android-sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- Check for working C compiler: C:/android-sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -
- broken
-- Configuring incomplete, errors occurred!
See also "C:/build/.cxx/cmake/Release/armeabi-v7a/CMakeFiles/CMakeOutput.log".
See also "C:/build/.cxx/cmake/Release/armeabi-v7a/CMakeFiles/CMakeError.log".
CMake Error at C:/android-sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "C:/android-sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/build/.cxx/cmake/Release/armeabi-v7a/CMakeFiles/CMakeTmp

    Run Build Command:"C:\android-sdk\cmake\3.10.2.4988404\bin\ninja" "cmTC_f2f6d"
    [1/2] Building C object CMakeFiles/cmTC_f2f6d.dir/testCCompiler.c.o
    FAILED: CMakeFiles/cmTC_f2f6d.dir/testCCompiler.c.o
    C:\android-sdk\ndk\21.1.6352462\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe --target=armv7-none-linux-andr
oideabi21 --gcc-toolchain=C:/android-sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/android-s
dk/ndk/21.1.6352462/toolchains/llvm/prebuilt/windows-x86_64/sysroot   -g -DANDROID -fdata-sections -ffunction-sections -
funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werr
or=format-security   -fPIE -o CMakeFiles/cmTC_f2f6d.dir/testCCompiler.c.o   -c testCCompiler.c
    ninja: build stopped: subcommand failed.

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

Exception in thread "main" java.io.IOException: Cmd '[C:\android-sdk\cmake\3.10.2.4988404\bin\cmake, -HC:\build\dex2c, -
DCMAKE_TOOLCHAIN_FILE=C:\android-sdk\ndk\21.1.6352462\build\cmake\android.toolchain.cmake, -DCMAKE_BUILD_TYPE=Release, -
DANDROID_ABI=armeabi-v7a, -DANDROID_NDK=C:\android-sdk\ndk\21.1.6352462, -DANDROID_PLATFORM=android-21, -DCMAKE_ANDROID_
ARCH_ABI=armeabi-v7a, -DCMAKE_ANDROID_NDK=C:\android-sdk\ndk\21.1.6352462, -DCMAKE_EXPORT_COMPILE_COMMANDS=ON, -DCMAKE_L
IBRARY_OUTPUT_DIRECTORY=C:\build\obj\armeabi-v7a, -DCMAKE_MAKE_PROGRAM=C:\android-sdk\cmake\3.10.2.4988404\bin\ninja, -D
CMAKE_SYSTEM_NAME=Android, -DCMAKE_SYSTEM_VERSION=21, -BC:\build\.cxx\cmake\Release\armeabi-v7a, -GNinja]' exec failed
        at com.nmmedit.apkprotect.BuildNativeLib.execCmd(BuildNativeLib.java:58)
        at com.nmmedit.apkprotect.BuildNativeLib.build(BuildNativeLib.java:22)
        at com.nmmedit.apkprotect.ApkProtect.generateNativeLibs(ApkProtect.java:199)
        at com.nmmedit.apkprotect.ApkProtect.run(ApkProtect.java:122)
        at com.nmmedit.protect.Main.main(Main.java:52)
PS C:\Users\Administrator>

**Comment by maoabc** [comment]
windows下可以使用, 这个错误应该是ndk有问题. 或者你可以手动在命令行执行相关命令, dex2c下就是转换后的c项目. 也可以用as随便建个项目,把dex2c复制到src/main下,然后gradle里配置cmake,
 externalNativeBuild {
        cmake {
            path 'src/main/dex2c/CMakeLists.txt'
        }
    }
用as来测试, 编译

**Comment by JAYAndroid** [comment]
感谢楼主的思路，问题已解决
原因是我的windows server缺少 C Runtime 动态库，安装后即可
https://www.microsoft.com/zh-CN/download/confirmation.aspx?id=49063
