### ISSUE TITLE
咨询个ARR加固问题

### ISSUE THREAD

**Issue by yinjihao** [maoabc/nmmp#46]
如果基于nmmp项目对AAR进行加固，需要修改哪些点，希望大佬指点下！

**Comment by maoabc** [comment]
需要先用d8把class文件转为classes.dex, 然后就是正常处理dex。之后用d8把dex再转为.class; 也可以记录处理过的方法，用java-asm直接处理转换前的class文件

**Comment by yinjihao** [comment]
我刚拉了AAR加固代码，对项目重新编译，执行gradle的jar task时，编译报错：
Execution failed for task ':jar'.
> Entry META-INF/versions/9/module-info.class is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.4/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.

aused by: org.gradle.api.GradleException: Could not expand ZIP '/Users/user/.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson/2.10/dd9b193aef96e973d5a11ab13cd17430c2e4306b/gson-2.10.jar'.
	at org.gradle.api.internal.file.archive.ZipFileTree.visit(ZipFileTree.java:108)
	at org.gradle.api.internal.file.collections.FilteredMinimalFileTree.visit(FilteredMinimalFileTree.java:92)

这个有遇到吗，新的aar加固你那里能编译成功吗，可以的话方便提供个jar包吗

**Comment by maoabc** [comment]
你可以看项目里的测试模块

mysterious ***@***.***> 于 2022年11月21日周一 19:59写道：
