### ISSUE TITLE
对aar中acitivity的onCreate方法加固后Crash，onCreate中findViewById对控件添加了点击事件

### ISSUE THREAD

**Issue by demomath** [maoabc/nmmp#66]
Caused by: java.lang.ArithmeticException: divide by zero
                                                                                                    	  at com.demo.test2.Test2Activity.onCreate(Native Method)
                                                                                                    	  at android.app.Activity.performCreate(Activity.java:7232)
                                                                                                    	  at android.app.Activity.performCreate(Activity.java:7221)
                                                                                                    	  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)

**Comment by maoabc** [comment]
没代码，没加固前后对比。
这个异常看着像代码本身的错误，除以0了。点击不点击事件基本没什么影响，只要处理生成的内部类class文件就行。

**Comment by frankgogoland** [comment]
aar加固还是很好用得，已经应用在产品上了，感谢作者。
