### ISSUE TITLE
不知道發生什麽了現在每一個軟件都跳Exception求大大幫忙。

### ISSUE THREAD

**Issue by LoveDoLove** [maoabc/nmmp#90]
java -jar vm-protect-2023-09-02-2034.jar apk test.apk
Exception in thread "main" java.util.zip.ZipException: Invalid CEN header (invalid zip64 extra data field size)
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1747)
        at java.base/java.util.zip.ZipFile$Source.checkExtraFields(ZipFile.java:1273)
        at java.base/java.util.zip.ZipFile$Source.checkAndAddEntry(ZipFile.java:1216)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1686)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1461)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1424)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:723)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:250)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:179)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:193)
        at com.nmmedit.apkprotect.util.ApkUtils.getFile(ApkUtils.java:35)
        at com.nmmedit.apkprotect.ApkProtect.run(ApkProtect.java:281)
        at com.nmmedit.protect.ApkMain.main(ApkMain.java:51)
        at com.nmmedit.protect.Main.main(Main.java:24)

**Comment by maoabc** [comment]
apk格式问题，部分zip处理使用java标准库的api，没法处理一些特殊的apk，可以重新使用标准zip重新打包。
不是很清楚java那个zip处理是否支持zip64，根本上解决应该全部换成zipflinger处理apk，以后有空再说。

**Comment by maoabc** [comment]
可以试试新版本，已经不再使用java.util.zip
