### ISSUE TITLE
小问题问一问

### ISSUE THREAD

**Issue by LoveDoLove** [maoabc/nmmp#91]
Termux能用吗?
我试了
有这个error
[/data/data/com.termux/files/usr/share/cmake-3.27.6/bin/cmake, -H/data/data/com.termux/files/home/dex2c/build/dex2c, -DCMAKE_TOOLCHAIN_FILE=/data/data/com.termux/files/usr/share/android-ndk-r23c/build/cmake/android.toolchain.cmake, -DCMAKE_BUILD_TYPE=Release, -DANDROID_ABI=armeabi-v7a, -DANDROID_NDK=/data/data/com.termux/files/usr/share/android-ndk-r23c/, -DANDROID_PLATFORM=android-21, -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a, -DCMAKE_ANDROID_NDK=/data/data/com.termux/files/usr/share/android-ndk-r23c/, -DCMAKE_EXPORT_COMPILE_COMMANDS=ON, -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/data/data/com.termux/files/home/dex2c/build/obj/sym/armeabi-v7a, -DCMAKE_MAKE_PROGRAM=/data/data/com.termux/files/usr/share/cmake-3.27.6/bin/ninja, -DCMAKE_SYSTEM_NAME=Android, -DCMAKE_SYSTEM_VERSION=21, -B/data/data/com.termux/files/home/dex2c/build/.cxx/cmake/Release/armeabi-v7a, -GNinja]
Exception in thread "main" java.io.IOException: Cannot run program "/data/data/com.termux/files/usr/share/cmake-3.27.6/bin/cmake": error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at com.nmmedit.apkprotect.BuildNativeLib.execCmd(BuildNativeLib.java:91)
        at com.nmmedit.apkprotect.BuildNativeLib.build(BuildNativeLib.java:68)
        at com.nmmedit.apkprotect.BuildNativeLib.generateNativeLibs(BuildNativeLib.java:51)
        at com.nmmedit.apkprotect.ApkProtect.run(ApkProtect.java:362)
        at com.nmmedit.protect.ApkMain.main(ApkMain.java:51)
        at com.nmmedit.protect.Main.main(Main.java:26)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
        ... 7 more

**Comment by maoabc** [comment]
自己保证ndk相关命令能正常使用就行，缺少什么命令补上就行，java部分没什么问题。

**Comment by TimScriptov** [comment]
@LoveDoLove Try CMake 3.18.1

New version not have "bin/ninja"
