### ISSUE TITLE
使用aab加固的时候报文件找不到问题

### ISSUE THREAD

**Issue by limaofang** [maoabc/nmmp#95]
Exception in thread "main" java.io.IOException: No mapping
	at com.nmmedit.apkprotect.deobfus.MappingReader.getMappingReader(MappingReader.java:27)
	at com.nmmedit.apkprotect.deobfus.MappingReader.parse(MappingReader.java:31)
	at com.nmmedit.apkprotect.dex2c.filters.ProguardMappingConfig.<init>(ProguardMappingConfig.java:37)
	at com.nmmedit.protect.AabMain.main(AabMain.java:40)
	at com.nmmedit.protect.Main.main(Main.java:27)

使用aab加固的时候报文件找不到问题，但mapping文件是存在的，但的确按照文档写的命令执行的 java -jar vm-protect-xxx.jar aab test.aab convertRules.txt，请问是什么问题导致的？

**Comment by maoabc** [comment]
map文件在哪呢？这个报错必然是找不到aab里的BUNDLE-METADATA/com.android.tools.build.obfuscation/proguard.map，如果有其他版本的aab结构另说。
