### ISSUE TITLE
AAR 编译加固后 调用报错 java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics

### ISSUE THREAD

**Issue by perfunctory** [maoabc/nmmp#99]
java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
at com.firtetrip.moohon.game.GameUtils.onCreate(Native Method)
at android.app.Activity.performCreate(Activity.java:8545)
at android.app.Activity.performCreate(Activity.java:8509)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1437)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3881)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4046)
 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2440)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:211)
at android.os.Looper.loop(Looper.java:300)
at android.app.ActivityThread.main(ActivityThread.java:8315)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

**Comment by perfunctory** [comment]
AAR加固后直接运行是正常的，签名打包就提示AAR里面的类报错，AAR里面代码使用java写的一个activity

**Comment by maoabc** [comment]
可能混淆规则问题，加固后导致一些依赖关系无法分析，去掉一些不该混淆的类。aar建议先用proguard混淆class后再加固。
